add prod deployment

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -196,15 +196,15 @@ pipeline {
 
                         i=1
                         while [ "$i" -le 30 ]; do
-                             STATUS=$(curl -sS --fail \
+                            STATUS=$(curl -sS --fail \
                             --request GET \
                             --url "https://api.render.com/v1/services/$SERVICE_ID/deploys/$DEPLOY_ID" \
                             --header "Authorization: Bearer $RENDER_API_KEY" \
                             | jq -r '.status')
 
-                            echo "$i - $SERVICE_NAME deployment status: $STATUS"
+                            echo "$SERVICE_NAME deployment status: $STATUS"
                             if [ "$STATUS" = "live" ]; then
-                                echo "✅ $SERVICE_NAME deployment is live!"
+                                echo "✅ $SERVICE_NAME deployment is live!🎉"
                                 return 0
                             fi
 
@@ -267,6 +267,84 @@ pipeline {
                         reportFiles: 'index.html',
                     ]
                 }
+            }
+        }
+
+        stage('Deploy Production') {
+            when {
+                expression {
+                    return env.GIT_BRANCH == 'origin/main'
+                }
+            }
+            environment {
+                DEPLOY_URL_BACKEND_PROD = credentials('RENDER_DEPLOY_BACKEND_PROD')
+                DEPLOY_URL_FRONTEND_PROD = credentials('RENDER_DEPLOY_FRONTEND_PROD')
+                RENDER_API_KEY = credentials('RENDER_API_KEY')
+                PROD_BACKEND_SERVICEID = credentials('PROD_BACKEND_SERVICEID')
+                PROD_FRONTEND_SERVICEID = credentials('PROD_FRONTEND_SERVICEID')
+            }
+            steps {
+                sh '''
+                    #!/bin/bash
+                    set -e
+
+                    deploy_and_wait() {
+                        DEPLOY_HOOK_URL=$1
+                        SERVICE_ID=$2
+                        SERVICE_NAME=$3
+
+                        echo "🚀 Start deployment for $SERVICE_NAME"
+                        DEPLOY_ID=$(curl "$DEPLOY_HOOK_URL" | jq -r '.deploy.id')
+
+                        if [ -z "$DEPLOY_ID" ] || [ "$DEPLOY_ID" = "null" ]; then
+                            echo "No deploy ID returned"
+                            exit 1
+                        fi
+
+                        # Poll deployment status every 5 seconds
+                        echo "⏱️Polling status of production deployment $DEPLOY_ID"
+
+                        i=1
+                        while [ "$i" -le 30 ]; do
+                            STATUS=$(curl -sS --fail \
+                            --request GET \
+                            --url "https://api.render.com/v1/services/$SERVICE_ID/deploys/$DEPLOY_ID" \
+                            --header "Authorization: Bearer $RENDER_API_KEY" \
+                            | jq -r '.status')
+
+                            echo "$SERVICE_NAME production deployment status: $STATUS"
+                            if [ "$STATUS" = "live" ]; then
+                                echo "✅ $SERVICE_NAME successfully deployed to production!🎉"
+                                return 0
+                            fi
+
+                            case "$STATUS" in
+                            *"failed"*|*"canceled"*|*"deactivated"*)
+                                echo "❌ $SERVICE_NAME failed to deploy to production with status: $STATUS"
+                                exit 1
+                                ;;
+                            esac
+
+                            sleep 5
+                            i=$((i + 1))
+                        done
+
+                        echo "$SERVICE_NAME deployment did not become live in production within expected time"
+                        exit 1
+                    }
+
+                    # Deploy backend first
+                    deploy_and_wait \
+                    "$DEPLOY_URL_BACKEND_PROD" \
+                    "$PROD_BACKEND_SERVICEID" \
+                    "bugtracker-backend-kamui"
+
+                    # Deploy frontend only if backend succeeded
+                    deploy_and_wait \
+                    "$DEPLOY_URL_FRONTEND_PROD" \
+                    "$PROD_FRONTEND_SERVICEID" \
+                    "bugtracker-frontend-kamui"
+                '''
             }
         }
     }
